version: '3.8'
services:

  postgres:
    image: postgres:14
    container_name: aw-postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

  nest-api:
    container_name: aw-test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres:
    name: aw-postgres-db
