-- AlterTable
ALTER TABLE "Item" ADD COLUMN     "amount" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "tokenId" INTEGER NOT NULL,
ALTER COLUMN "price" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "wallet" TEXT NOT NULL,
ALTER COLUMN "balance" DROP DEFAULT,
ALTER COLUMN "balance" SET DATA TYPE DOUBLE PRECISION;
